id: I67772257
ocr_import_info:
  timestamp: '2023-08-16T06:25:56.816186+00:00'
  batch_id: batch-0b93
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-16 07:58:54.360102+00:00
last_modified: 2023-08-16 07:58:54.360110+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22330
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22330
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བའི་གཞུང་འགྲེལ་རིགས་པའི་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་རྫིངས།
  languages:
  - bo
  author: ལེགས་པ་ཆོས་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.9293141859847126
  ocr_word_median_confidence_index: 0.98379743
bases:
  I3CN22336:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22336
      total_pages: 900
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN22336.txt
    statistics:
      ocr_word_median_confidence_index: 0.98379743
      ocr_word_mean_confidence_index: 0.9293141859847126
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
